### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by vivek3141** [ppaquette/gym-super-mario#23]
I have SDL installed and installed this using pip. I'm running python 3.6 and ubuntu 18.04. When I try 
```import ppaquette_gym_super_mario, gym
env = gym.make('ppaquette/SuperMarioBros-1-1-v0')

done = True
for step in range(5000):
    if done:
        state = env.reset()
    state, reward, done, info = env.step(env.action_space.sample())
    env.render()

env.close()
```
I get 
```Traceback (most recent call last):
  File "/home/vivnp/Python Projects/super-mario-ai/test.py", line 15, in <module>
    env.render()
  File "/home/vivnp/.local/lib/python3.6/site-packages/gym/core.py", line 284, in render
    return self.env.render(mode)
  File "/home/vivnp/.local/lib/python3.6/site-packages/gym/core.py", line 111, in render
    raise NotImplementedError
NotImplementedError
Exception ignored in: <module 'threading' from '/usr/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt 
```
I have tried installing pyglet 1.2.4, and making a new python environment and installing it there, to no avail.
Any suggestions?

**Comment by vivek3141** [comment]
Fixed just remove env.render()
