### ISSUE TITLE
Type Error 'int object is not subscriptable'

### ISSUE THREAD

**Issue by amay1212** [ppaquette/gym-super-mario#24]
Im getting this error while running 

**env = gym.make('SuperMarioBros-1-1-v0')**

Error : 

[2018-08-20 08:38:48,607] Making new env: SuperMarioBros-1-1-v0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/universe-starter-agent/lib/python3.5/site-packages/gym/envs/registration.py", line 161, in make
    return registry.make(id)
  File "/anaconda3/envs/universe-starter-agent/lib/python3.5/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/anaconda3/envs/universe-starter-agent/lib/python3.5/site-packages/gym/envs/registration.py", line 86, in make
    env = cls(**self._kwargs)
  File "/anaconda3/envs/universe-starter-agent/lib/python3.5/site-packages/gym/envs/ppaquette_gym_super_mario/super_mario_bros.py", line 256, in __init__
    num_levels=32)
  File "/anaconda3/envs/universe-starter-agent/lib/python3.5/site-packages/gym/envs/ppaquette_gym_super_mario/nes_env.py", line 548, in __init__
    NesEnv.__init__(self)
  File "/anaconda3/envs/universe-starter-agent/lib/python3.5/site-packages/gym/envs/ppaquette_gym_super_mario/nes_env.py", line 48, in __init__
    self.action_space = spaces.MultiDiscrete([1] * NUM_ACTIONS)
  File "/anaconda3/envs/universe-starter-agent/lib/python3.5/site-packages/gym/spaces/multi_discrete.py", line 29, in __init__
    print(array_of_param_array)
  File "/anaconda3/envs/universe-starter-agent/lib/python3.5/site-packages/gym/spaces/multi_discrete.py", line 29, in <listcomp>
    print(array_of_param_array)
TypeError: 'int' object is not subscriptable

**Comment by danielnbarbosa** [comment]
Try using gym 0.10.5.  That's what worked for me: `pip install gym==0.10.5`
